name: aymjnd blog
url: https://aymjnd.com
description: post-it notes

permalink: /:year/:month/:day/:title/
paginate: 5

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
